name: Node CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ["4.2"]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: ${{ matrix.mongodb-version }}
    - name: npm install
      run: |
        npm i
      env:
        CI: true
        EAZIN_RC_PATH: ./test/ci.eazinrc.js
    - name: npm unit test
      run: |
        npm run test:unit
      env:
        CI: true
        EAZIN_RC_PATH: ./test/ci.eazinrc.js
    - name: npm E2E test
      run: |
        npm run build:html
        npm run test:e2e
      env:
        CI: true
        EAZIN_RC_PATH: ./test/ci.eazinrc.js
        JEST_SERVE: 3030
        TEST_SENDER_FILE: /tmp/eazin-testsender.json
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test-results
        path: test-results
